### ISSUE TITLE
Hotkey exception

### ISSUE THREAD

**Issue by simonegiacomelli** [simonegiacomelli/pynanto2#7]
Probably it's best to check the type of the event?
```
Uncaught PythonError: Traceback (most recent call last):
  File "/default_bundle/pynanto/remote/hotkey.py", line 20, in _detect_hotkey
    if e.ctrlKey: key += 'CTRL-'
AttributeError: ctrlKey

    at new_error (pyodide.asm.js:10:218123)
    at pyodide.asm.wasm:0xdef7c
    at pyodide.asm.wasm:0xdf077
    at Module._pythonexc2js (pyodide.asm.js:10:900301)
    at Module.callPyObjectKwargs (pyodide.asm.js:10:119233)
    at Module.callPyObject (pyodide.asm.js:10:119442)
    at PyProxyClass.apply (pyodide.asm.js:10:126886)
    at Object.apply (pyodide.asm.js:10:125914)
```

**Comment by simonegiacomelli** [comment]
It happens when the password manager auto fills the username/password
This is an event that causes the execption
![image](https://user-images.githubusercontent.com/3785783/222974177-0785eadd-4d4f-4fbe-8647-bbd912f11c6b.png)
